### ISSUE TITLE
no https url in firefox.sh

### ISSUE THREAD

**Issue by HaQadosch** [baldurbjarnason/uncluttered-mocha-setup#1]
In `https://the-raggedy-dev.teachable.com/courses/uncluttered-test-driven-web-development/lectures/50520258`

- the url should be `http://` and not `https://` 
- the `-no-remote` option makes `-new-instance` redundant
- adding `-url` option adds more clarity (completely subjectif)

```sh
# CLI options detailed here https://wiki.mozilla.org/Firefox/CommandLineOptions
DATA_DIR="$(mktemp -d -t 'firefox-unsafe_data_dir.XXXXXXXXXX')"
"${FIREFOX}" \
  -profile $DATA_DIR \
  -no-remote \
  -url http://localhost:8888/ \
  >/dev/null 2>&1 &!
```

**Comment by baldurbjarnason** [comment]
Ah, you're absolutely correct.

Thanks for taking the time to submit an issue. I really appreciate it. It should be fixed now.
